#' NutrientModeling: A package to generate nutrient content data for
#' diets generated by the IMPACT model
#' The NutrientModeling package provides several categories of important functions:
#' foo, bar and baz.
#'
#' @section NutrientModeling functions:
#' The NutrientModeling functions ...
#'
